# Generated by Django 3.0.9 on 2021-05-08 10:32

from django.db import migrations
from django.apps.registry import Apps

from django.contrib.auth.hashers import PBKDF2SHA1PasswordHasher


def initAdmin(app: Apps, schema_editor):
    admin = app.get_model('data_access', 'User')()
    admin.username = 'admin'
    admin.password = PBKDF2SHA1PasswordHasher().encode('123456', 'salt', 180000)
    admin.personnel_number = 0
    admin.position = 'Администратор'
    admin.is_leading = True
    admin.email = 'admin@localhost'
    admin.is_superuser = True
    admin.phone = '+79008007060'
    admin.is_staff = True
    admin.save()

def initAdminReverse(app: Apps, schema_editor):
    app.get_model('data_access', 'User').objects.get(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initAdmin, initAdminReverse)
    ]
