# Generated by Django 3.0.9 on 2021-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0002_init_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата обмена информацией'),
        ),
    ]
